Repository spacetelescope/cubeviz, pull requests merged in 2018-04, with the labels that each got.

#380 Improve how we override the image viewer state to avoid duplicating code
  cubeviz/image_viewer.py
Labels: cleanup

#382 Fix undefined variable
  cubeviz/controls/flux_units.py
Labels: bug

#383 Fix setup import bug
  cubeviz/__init__.py
  cubeviz/_internal_init.py
  setup.py
Labels: bug

#406 Do not perform fast draw if slice index did not change
  cubeviz/image_viewer.py
  cubeviz/tests/test_ui.py
Labels: needed on 0.2.x

#415 Don't use the glue overlay infrastructure for now
  cubeviz/tools/common.py
Labels: needed on 0.2.x

#414 Units patch
  cubeviz/__init__.py
  cubeviz/controls/flux_units.py
  cubeviz/flux_equivalences.py
Labels: needed on 0.2.x
